name: jest-and-docker-ci

on: push

jobs:
  test-front:
    runs-on: ubuntu-latest
    steps:
      # Retrieve code from the repository
      - name: Check out code
        uses: actions/checkout@v4
      # Run the client tests
      - name: Goto client and run tests
        run: cd client && npm i && npm test
  docker:
    # For this job to run, the `test-front` job must be completed successfully (sequential execution).
    needs: test-front
    # This job will only run when the push is made to the `main` branch (additional condition)
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      # Enable multi-platform builds within Docker workflows by installing QEMU static binaries.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # Create and boot a builder to be used in the following steps.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Log in to Docker Hub using personal access token.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and push the Docker image to Docker Hub using Buildx. By default, this actions use the Git context so there i no need to use the `actions/checkout` action to check out the repository as this will ne done directly by BuildKit.
      - name: Build and push
        uses: docker/build-push-action@v6
        # Add Docker build context (location of the Dockerfile) and tags to the image.
        with:
          push: true
          context: "{{defaultContext}}:client"
          tags: ${{ vars.DOCKERHUB_USERNAME }}/quete1902:latest
